---
title: BaseKit Brand Guidelines
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    image: "/assets/placeholder-social.png"
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: "/assets/placeholder-social.png"
exclude:
- README.md
- CNAME
- Gemfile
- Gemfile.lock
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
jekyll-mentions: https://twitter.com
twitter:
  username: BaseKit
author: BaseKit
social:
  name: BaseKit
  links:
  - https://twitter.com/BaseKit
  - https://www.facebook.com/TeamBaseKit
  - https://www.linkedin.com/company-beta/744383/
  - https://plus.google.com/+BaseKit
  - https://github.com/BaseKit
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
encoding: utf-8
logo: "/assets/logo.svg"
description: Official brand guidelines for the BaseKit platform
url: http://basekitbrand.com
repo: https://github.com/basekit/basekitbrand.com
email: info@basekit.com
avatarurl: https://avatars0.githubusercontent.com/u/1006602
navigation_header:
  Search: "/search/"
  About: "/about/"
  Home: "/"
navigation_aside:
  Logo: "/logo/"
  Colours: "/colours/"
  Typography: "/typography/"
  Iconography: "/iconography/"
  Photography: "/photography/"
  Videos: "/videos/"
  Other resources: "/other/"
navigation_footer:
  BaseKit website: http://basekit.com
social_links:
  Twitter: https://twitter.com/BaseKit
  Facebook: https://www.facebook.com/TeamBaseKit
  LinkedIn: https://www.linkedin.com/company-beta/744383/
  Google+: https://plus.google.com/+BaseKit
  GitHub: https://github.com/BaseKit
